/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface XzalabaijAmbulanceWlList {
    }
}
declare global {
    interface HTMLXzalabaijAmbulanceWlListElement extends Components.XzalabaijAmbulanceWlList, HTMLStencilElement {
    }
    var HTMLXzalabaijAmbulanceWlListElement: {
        prototype: HTMLXzalabaijAmbulanceWlListElement;
        new (): HTMLXzalabaijAmbulanceWlListElement;
    };
    interface HTMLElementTagNameMap {
        "xzalabaij-ambulance-wl-list": HTMLXzalabaijAmbulanceWlListElement;
    }
}
declare namespace LocalJSX {
    interface XzalabaijAmbulanceWlList {
    }
    interface IntrinsicElements {
        "xzalabaij-ambulance-wl-list": XzalabaijAmbulanceWlList;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "xzalabaij-ambulance-wl-list": LocalJSX.XzalabaijAmbulanceWlList & JSXBase.HTMLAttributes<HTMLXzalabaijAmbulanceWlListElement>;
        }
    }
}
